-- IRIS demo data.
--
-- 7 departments, 1 HR admin, 4 HODs, 2 staff, 1 CEO. Every account uses the
-- password
-- Password123! — development only.
--
-- Submissions cover 2025 in full and 2026 up to the current month (July),
-- spanning every status: approved, pending HOD, pending HR, returned,
-- rejected, overdue, and nil return. Monthly hours vary widely enough that the
-- compliance dashboard shows genuine spread rather than a flat line.
--
-- public.users.id, public.departments.id and every other key in this schema is
-- generated by the database, so nothing here can name an id up front. Rows are
-- resolved by email for people and by name for departments — the two natural
-- keys the schema already declares unique. The auth.users uuids stay literal:
-- that table belongs to Supabase Auth and keys on uuid, and fixed values make a
-- re-run reuse the same accounts rather than accumulate new ones.

create extension if not exists pgcrypto with schema extensions;

set search_path = public, extensions;

-- ---------------------------------------------------------------------------
-- Account creation helper. Writes the auth.users and auth.identities rows that
-- GoTrue needs for email/password sign-in, then the matching profile, and
-- returns the integer id the database assigned that profile.
-- ---------------------------------------------------------------------------

create or replace function public.seed_account(
  p_auth_id uuid,
  p_email text,
  p_full_name text,
  p_designation text,
  p_role public.user_role,
  p_department_name text,
  p_hod_email text,
  p_date_joined date
)
returns integer
language plpgsql
as $$
declare
  v_user_id integer;
begin
  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password,
    email_confirmed_at, created_at, updated_at,
    confirmation_token, email_change, email_change_token_new, recovery_token,
    raw_app_meta_data, raw_user_meta_data
  ) values (
    '00000000-0000-0000-0000-000000000000', p_auth_id, 'authenticated', 'authenticated',
    p_email, extensions.crypt('Password123!', extensions.gen_salt('bf')),
    now(), now(), now(),
    '', '', '', '',
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('full_name', p_full_name)
  )
  on conflict (id) do nothing;

  insert into auth.identities (
    id, user_id, identity_data, provider, provider_id,
    last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(), p_auth_id,
    jsonb_build_object('sub', p_auth_id::text, 'email', p_email),
    'email', p_auth_id::text,
    now(), now(), now()
  )
  on conflict do nothing;

  insert into public.users (
    auth_user_id, full_name, email, designation, date_joined,
    role, department_id, hod_id, is_active
  ) values (
    p_auth_id, p_full_name, p_email, p_designation, p_date_joined,
    p_role,
    (select id from public.departments where name = p_department_name),
    (select id from public.users where email = p_hod_email),
    true
  )
  on conflict (email) do nothing;

  select id into v_user_id from public.users where email = p_email;
  return v_user_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Departments and people
-- ---------------------------------------------------------------------------

insert into public.departments (name) values
  ('Sales'),
  ('R&D'),
  ('Support'),
  ('HR'),
  ('Finance'),
  ('Support Engineer'),
  ('Admin')
on conflict (name) do nothing;

-- The four HODs are created without a reporting line because they reference
-- each other; the cross-links are set once every row exists.
select public.seed_account(
  '22222222-2222-2222-2222-222222222222', 'ks@irs.com.my',
  'Chng Kok Sheng', 'Head of R&D', 'hod',
  'R&D', null, date '2016-04-11'
);

select public.seed_account(
  '33333333-3333-3333-3333-333333333333', 'joshua@irs.com.my',
  'Joshua', 'Head of Support', 'hod',
  'Support', null, date '2017-02-06'
);

select public.seed_account(
  '44444444-4444-4444-4444-444444444444', 'chen@irs.com.my',
  'Ms. Chen', 'Head of Finance', 'hod',
  'Finance', null, date '2015-09-14'
);

select public.seed_account(
  '55555555-5555-5555-5555-555555555555', 'lee@irs.com.my',
  'Ms. Lee', 'Head of HR', 'hod',
  'HR', null, date '2016-11-21'
);

-- A HOD files a monthly record too, and that record still needs a HOD stage
-- before it reaches HR. They are paired so each is verified by another HOD:
-- the CEO cannot do it, because the CEO approves nothing.
update public.users
   set hod_id = (select id from public.users where email = 'joshua@irs.com.my')
 where email = 'ks@irs.com.my';

update public.users
   set hod_id = (select id from public.users where email = 'ks@irs.com.my')
 where email = 'joshua@irs.com.my';

update public.users
   set hod_id = (select id from public.users where email = 'lee@irs.com.my')
 where email = 'chen@irs.com.my';

update public.users
   set hod_id = (select id from public.users where email = 'chen@irs.com.my')
 where email = 'lee@irs.com.my';

-- Joshua heads four departments; the others head one each.
update public.departments
   set hod_id = (select id from public.users where email = 'ks@irs.com.my')
 where name = 'R&D';

update public.departments
   set hod_id = (select id from public.users where email = 'joshua@irs.com.my')
 where name in ('Support', 'Sales', 'Admin', 'Support Engineer');

update public.departments
   set hod_id = (select id from public.users where email = 'chen@irs.com.my')
 where name = 'Finance';

update public.departments
   set hod_id = (select id from public.users where email = 'lee@irs.com.my')
 where name = 'HR';

-- HR administers the system and sits in the HR department, so their own
-- monthly record is verified by the head of HR before HR approves it.
select public.seed_account(
  '11111111-1111-1111-1111-111111111111', 'hr@irs.com.my',
  'Nurul Aina Binti Rahim', 'HR Manager', 'hr_admin',
  'HR', 'lee@irs.com.my', date '2019-03-04'
);

-- Two staff placeholders. The roster above is heads of department only, and
-- staff are the people the training module is actually for — without at least
-- one, there is no one to demonstrate the main flow as, and no subject for the
-- tests that check an employee cannot see a colleague's records. Rename these
-- to real employees when the roster is known.
select public.seed_account(
  '77777777-7777-7777-7777-777777777777', 'staff.rnd@irs.com.my',
  'Demo Staff (R&D)', 'Software Engineer', 'staff',
  'R&D', 'ks@irs.com.my', date '2022-05-09'
);

select public.seed_account(
  '88888888-8888-8888-8888-888888888888', 'staff.support@irs.com.my',
  'Demo Staff (Support)', 'Support Specialist', 'staff',
  'Support', 'joshua@irs.com.my', date '2023-01-16'
);

-- The CEO reviews and reports. No department and no reporting line, because
-- the CEO neither submits a record nor approves anyone else's.
select public.seed_account(
  '66666666-6666-6666-6666-666666666666', 'polak@irs.com.my',
  'Polak', 'Chief Executive Officer', 'ceo',
  null, null, date '2014-01-06'
);

-- ---------------------------------------------------------------------------
-- Submission generation
--
-- Each person gets a base monthly volume, so the company shows a spread from
-- comfortably above the 48h standard down to below the 36h threshold.
-- ---------------------------------------------------------------------------

-- A real table rather than a temporary one. Temp tables are session-scoped, and
-- the Supabase SQL Editor does not guarantee a single session across a script,
-- so a temp table can vanish before the generator below reads it. Dropped
-- explicitly at the end of this file.
create table public.seed_people (
  idx int,
  id integer,
  base_minutes int,
  catalogue text
);

-- idx drives the deterministic variance below, so it is stated here rather than
-- taken from users.id: the shape of the demo data must not depend on the order
-- the database happened to assign keys in.
insert into public.seed_people (idx, id, base_minutes, catalogue)
select v.idx, u.id, v.base_minutes, v.catalogue
  from (values
    (0, 'ks@irs.com.my',     315, 'lead'),
    (1, 'joshua@irs.com.my', 260, 'lead'),
    (2, 'chen@irs.com.my',   200, 'lead'),
    (3, 'lee@irs.com.my',    170, 'lead'),
    (4, 'staff.rnd@irs.com.my',     290, 'engineering'),
    (5, 'staff.support@irs.com.my', 165, 'support'),
    -- HR records training of its own too.
    (6, 'hr@irs.com.my',            235, 'lead')
  ) as v (idx, email, base_minutes, catalogue)
  join public.users u on u.email = v.email;

do $$
declare
  person record;
  v_hr integer;
  v_year int;
  v_month int;
  v_status public.submission_status;
  v_nil boolean;
  v_minutes int;
  v_submission integer;
  v_submitted timestamptz;
  v_late boolean;
  v_hod integer;
  v_entry_count int;
  v_entry int;
  v_entry_minutes int;
  v_remaining int;
  v_day int;
  v_start timestamptz;
  v_titles text[];
  v_providers text[];
  v_title text;
  v_provider text;
  v_effectiveness public.training_effectiveness;
  v_variance int;
begin
  select id into v_hr from public.users where email = 'hr@irs.com.my';

  for person in select * from public.seed_people order by idx loop

    select hod_id into v_hod from public.users where id = person.id;

    v_titles := case person.catalogue
      when 'engineering' then array[
        'Secure coding practices workshop',
        'PostgreSQL performance tuning',
        'Automated testing with Playwright',
        'Clean architecture in TypeScript',
        'Incident response drill',
        'Accessibility fundamentals for web apps'
      ]
      when 'sales' then array[
        'Consultative selling techniques',
        'CRM pipeline management refresher',
        'Negotiation skills workshop',
        'Product update briefing',
        'Key account planning',
        'Proposal writing clinic'
      ]
      when 'support' then array[
        'Customer service excellence',
        'Ticket triage and escalation',
        'Troubleshooting methodology',
        'Product update briefing',
        'Handling difficult conversations',
        'Knowledge base authoring'
      ]
      else array[
        'Performance management essentials',
        'Coaching and feedback skills',
        'Employment law update',
        'Budget planning workshop',
        'Leading hybrid teams',
        'Data protection and PDPA briefing'
      ]
    end;

    v_providers := array[
      'Internal — IRS Academy',
      'SIRIM Training Services',
      'Coursera',
      'Malaysian Institute of Management',
      'Vendor-led session',
      'Internal — knowledge sharing'
    ];

    for v_year in 2025..2026 loop
      for v_month in 1..12 loop

        -- 2026 has not happened past July.
        exit when v_year = 2026 and v_month > 7;

        v_nil := false;
        v_late := false;
        v_variance := ((person.idx * 7 + v_month * 13) % 5) * 30;
        v_minutes := person.base_minutes + v_variance - 60;

        -- Default: fully processed history.
        v_status := 'approved';

        -- A quiet month with nothing to report.
        if (person.idx + v_month) % 11 = 0 then
          v_nil := true;
          v_minutes := 0;
        end if;

        -- The current year's recent months are still moving through the flow.
        if v_year = 2026 then
          if v_month = 7 then
            -- July 2026 is the current month: every live state is present.
            v_status := case person.idx % 6
              when 0 then 'submitted_pending_hod'
              when 1 then 'hod_verified'
              when 2 then 'draft'
              when 3 then 'submitted_pending_hod'
              when 4 then 'hod_verified'
              else 'draft'
            end;
          elsif v_month = 6 then
            -- June closed on 10 July, so anything unfinished is now overdue.
            v_status := case person.idx % 7
              when 0 then 'returned_by_hod'
              when 1 then 'rejected'
              when 2 then 'draft'
              when 5 then 'submitted_pending_hod'
              else 'approved'
            end;
          elsif v_month = 5 and person.idx % 4 = 1 then
            v_status := 'hod_verified';
          end if;
        end if;

        -- Two people simply never opened a couple of months.
        if v_year = 2026 and v_month = 7 and person.idx in (7, 9) then
          continue;
        end if;

        if v_status = 'draft' then
          v_submitted := null;
        else
          -- Most people file in the first week of the following month.
          v_day := 2 + ((person.idx * 3 + v_month) % 12);
          v_late := v_day > 10;
          v_submitted := make_timestamptz(
            case when v_month = 12 then v_year + 1 else v_year end,
            case when v_month = 12 then 1 else v_month + 1 end,
            v_day, 9 + (person.idx % 8), 15, 0
          );
        end if;

        insert into public.training_submissions (
          employee_id, month, year, status, is_nil_return,
          submitted_at, is_late,
          hod_verified_by, hod_verified_at, hod_comment,
          hr_verified_by, hr_verified_at, hr_comment
        ) values (
          person.id, v_month, v_year, v_status, v_nil,
          v_submitted, v_late,
          case
            when v_status in ('hod_verified', 'approved', 'rejected', 'returned_by_hod')
            then v_hod
          end,
          case
            when v_status in ('hod_verified', 'approved', 'rejected', 'returned_by_hod')
            then v_submitted + interval '2 days'
          end,
          case
            when v_status = 'returned_by_hod'
            then 'The October conference entry has no certificate attached. Please add it and resubmit.'
            when v_status = 'approved' and v_month % 5 = 0
            then 'Good spread of technical and soft-skill training this month.'
          end,
          case
            when v_status in ('approved', 'rejected')
            then v_hr
          end,
          case
            when v_status in ('approved', 'rejected') then v_submitted + interval '4 days'
          end,
          case
            when v_status = 'rejected'
            then 'Recorded hours do not match the attendance sheet. Please correct the duration and resubmit.'
          end
        )
        returning id into v_submission;

        continue when v_nil;

        -- Split the month across one or two entries.
        v_entry_count := case when v_minutes > 240 then 2 else 1 end;
        v_remaining := v_minutes;

        for v_entry in 1..v_entry_count loop
          if v_entry = v_entry_count then
            v_entry_minutes := v_remaining;
          else
            v_entry_minutes := (v_minutes / 2 / 15) * 15;
            v_remaining := v_remaining - v_entry_minutes;
          end if;

          exit when v_entry_minutes <= 0;

          v_title := v_titles[1 + ((person.idx + v_month + v_entry) % array_length(v_titles, 1))];
          v_provider := v_providers[1 + ((person.idx + v_entry) % array_length(v_providers, 1))];
          v_effectiveness := case (person.idx + v_month + v_entry) % 6
            when 0 then 'average'
            when 3 then 'average'
            when 5 then 'not_effective'
            else 'effective'
          end;

          v_day := 3 + ((person.idx * 2 + v_month * 5 + v_entry * 7) % 22);
          v_start := make_timestamptz(v_year, v_month, v_day, 9, 0, 0);

          insert into public.training_records (
            submission_id, seq_no, title,
            start_datetime, end_datetime,
            calculated_minutes, recorded_minutes, override_reason,
            location, trainer_provider, effectiveness, remarks
          ) values (
            v_submission, v_entry, v_title,
            v_start, v_start + make_interval(mins => v_entry_minutes),
            v_entry_minutes, v_entry_minutes, null,
            case (person.idx + v_entry) % 3
              when 0 then 'IRS Training Room, Cyberjaya'
              when 1 then 'Online — Microsoft Teams'
              else 'Client site, Kuala Lumpur'
            end,
            v_provider, v_effectiveness,
            case when v_entry = 1 and v_month % 4 = 0
              then 'Applied to the current sprint work.'
            end
          );
        end loop;

      end loop;
    end loop;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- The multi-day override case from the source workbook.
--
-- A course running 26-27 February, 09:00-17:00 each day, is 16 hours gross.
-- Chng Kok Sheng recorded 14 because the two lunch breaks are not learning.
-- This is the case reviewers must be able to see and question.
-- ---------------------------------------------------------------------------

do $$
declare
  v_submission integer;
  v_next_seq int;
begin
  select s.id into v_submission
    from public.training_submissions s
    join public.users u on u.id = s.employee_id
   where u.email = 'ks@irs.com.my'
     and s.month = 2 and s.year = 2026;

  if v_submission is null then
    return;
  end if;

  select coalesce(max(seq_no), 0) + 1 into v_next_seq
    from public.training_records
   where submission_id = v_submission;

  insert into public.training_records (
    submission_id, seq_no, title,
    start_datetime, end_datetime,
    calculated_minutes, recorded_minutes, override_reason,
    location, trainer_provider, effectiveness, remarks
  ) values (
    v_submission, v_next_seq,
    'Advanced PostgreSQL administration (2 days)',
    make_timestamptz(2026, 2, 26, 9, 0, 0),
    make_timestamptz(2026, 2, 27, 17, 0, 0),
    960, 840,
    'Excludes the one-hour lunch break on each of the two days.',
    'SIRIM Training Centre, Shah Alam',
    'SIRIM Training Services',
    'effective',
    'Certificate issued on completion.'
  );
end;
$$;

-- A second override, so the reviewer view is exercised for more than one person.
do $$
declare
  v_submission integer;
  v_next_seq int;
begin
  select s.id into v_submission
    from public.training_submissions s
    join public.users u on u.id = s.employee_id
   where u.email = 'ks@irs.com.my'
     and s.month = 4 and s.year = 2026;

  if v_submission is null then
    return;
  end if;

  select coalesce(max(seq_no), 0) + 1 into v_next_seq
    from public.training_records
   where submission_id = v_submission;

  insert into public.training_records (
    submission_id, seq_no, title,
    start_datetime, end_datetime,
    calculated_minutes, recorded_minutes, override_reason,
    location, trainer_provider, effectiveness, remarks
  ) values (
    v_submission, v_next_seq,
    'Regional sales kick-off (3 days)',
    make_timestamptz(2026, 4, 14, 9, 0, 0),
    make_timestamptz(2026, 4, 16, 17, 0, 0),
    1440, 990,
    'Excludes lunch breaks and the social programme on the final afternoon.',
    'Hotel Istana, Kuala Lumpur',
    'Internal — IRS Academy',
    'effective',
    null
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Seed the audit trail so the HR activity feed is not empty on first run.
-- ---------------------------------------------------------------------------

insert into public.automation_logs (
  action_type, description, related_table, related_id, performed_by, is_system, created_time
)
select
  case s.status
    when 'approved' then 'submission.approved'
    when 'rejected' then 'submission.rejected'
    when 'hod_verified' then 'submission.hod_verified'
    when 'returned_by_hod' then 'submission.returned'
    else 'submission.submitted'
  end,
  format(
    '%s — %s %s',
    p.full_name,
    to_char(make_date(s.year, s.month, 1), 'FMMonth'),
    s.year
  ),
  'training_submissions',
  s.id,
  coalesce(s.hr_verified_by, s.hod_verified_by, s.employee_id),
  false,
  coalesce(s.hr_verified_at, s.hod_verified_at, s.submitted_at, s.created_time)
from public.training_submissions s
join public.users p on p.id = s.employee_id
where s.status <> 'draft';

drop table public.seed_people;

drop function public.seed_account(
  uuid, text, text, text, public.user_role, text, text, date
);

-- ---------------------------------------------------------------------------
-- Requests — prototype module demo data.
--
-- Ten requests spanning every status, category and priority, so the list
-- filters and the dashboard tiles have a real spread to show. Costs are stored
-- in cents: RM 890.00 is 89000.
-- ---------------------------------------------------------------------------

insert into public.requests (
  requester_id, title, description, category, estimated_cost_cents,
  attachment_name, priority, assigned_department, approval_required, status,
  ai_suggestion, reviewed_by, reviewed_at, review_comment, created_time
) values
  ((select id from public.users where email = 'ks@irs.com.my'),
   'Second monitor for development work',
   'I need a new monitor because my current monitor is too small for reviewing code side by side.',
   'it_equipment', 89000, null, 'normal', 'IT', true, 'approved',
   '{"category":"it_equipment","department":"IT","priority":"normal","approvalRequired":true,"reason":"Equipment purchase usually requires manager or admin approval."}'::jsonb,
   (select id from public.users where email = 'hr@irs.com.my'),
   now() - interval '26 days', 'Approved. Collect from the IT store room.',
   now() - interval '28 days'),

  ((select id from public.users where email = 'joshua@irs.com.my'),
   'Laptop will not power on',
   'My laptop is broken and will not start, I cannot work until it is repaired.',
   'it_equipment', 0, 'fault-report.pdf', 'urgent', 'IT', true, 'completed',
   '{"category":"it_equipment","department":"IT","priority":"urgent","approvalRequired":true,"reason":"Wording suggests work is blocked, so this is raised as urgent."}'::jsonb,
   (select id from public.users where email = 'hr@irs.com.my'),
   now() - interval '20 days', 'Replacement unit issued while the board is repaired.',
   now() - interval '21 days'),

  ((select id from public.users where email = 'chen@irs.com.my'),
   'Ergonomic chair replacement',
   'My chair is damaged and the back support no longer holds position.',
   'office_furniture', 65000, null, 'high', 'Admin', true, 'in_progress',
   '{"category":"office_furniture","department":"Admin","priority":"high","approvalRequired":true,"reason":"Replacement of damaged furniture is treated as high priority."}'::jsonb,
   (select id from public.users where email = 'hr@irs.com.my'),
   now() - interval '9 days', 'Approved, waiting on the supplier delivery.',
   now() - interval '12 days'),

  ((select id from public.users where email = 'lee@irs.com.my'),
   'JetBrains licence for backend work',
   'Please install and license the JetBrains IDE on my workstation.',
   'software', 74000, null, 'normal', 'IT', true, 'pending_approval',
   '{"category":"software","department":"IT","priority":"normal","approvalRequired":true,"reason":"Software licences are purchased centrally and need approval."}'::jsonb,
   null, null, null, now() - interval '4 days'),

  ((select id from public.users where email = 'ks@irs.com.my'),
   'Name cards for client visits',
   'I need business cards printed with my new designation for upcoming client visits.',
   'name_card', 12000, null, 'normal', 'Admin', true, 'approved',
   '{"category":"name_card","department":"Admin","priority":"normal","approvalRequired":true,"reason":"Printed stationery is ordered by Admin in batches."}'::jsonb,
   (select id from public.users where email = 'hr@irs.com.my'),
   now() - interval '6 days', 'Approved, going out with the next print batch.',
   now() - interval '8 days'),

  ((select id from public.users where email = 'joshua@irs.com.my'),
   'Access card not opening the back door',
   'My access card has stopped working on the rear entrance, I have an access issue every morning.',
   'access_card', 0, null, 'high', 'Admin', false, 'in_progress',
   '{"category":"access_card","department":"Admin","priority":"high","approvalRequired":false,"reason":"Access problems are handled directly by Admin without a purchase approval."}'::jsonb,
   null, null, null, now() - interval '3 days'),

  ((select id from public.users where email = 'chen@irs.com.my'),
   'Air conditioning in the support room',
   'The aircond in the support area is not cooling and needs maintenance.',
   'maintenance', 0, null, 'high', 'Facilities', false, 'submitted',
   '{"category":"maintenance","department":"Facilities","priority":"high","approvalRequired":false,"reason":"Building maintenance is raised directly with Facilities."}'::jsonb,
   null, null, null, now() - interval '1 day'),

  ((select id from public.users where email = 'lee@irs.com.my'),
   'Standing desk converter',
   'A standing desk converter would be nice to have for the afternoons.',
   'office_furniture', 45000, null, 'low', 'Admin', true, 'rejected',
   '{"category":"office_furniture","department":"Admin","priority":"low","approvalRequired":true,"reason":"Described as nice to have, so raised at low priority."}'::jsonb,
   (select id from public.users where email = 'hr@irs.com.my'),
   now() - interval '14 days',
   'Not in this quarter budget. Please raise again in the next cycle.',
   now() - interval '16 days'),

  ((select id from public.users where email = 'ks@irs.com.my'),
   'Stationery for the sprint board',
   'Whiteboard markers, sticky notes and index cards for the team planning wall.',
   'office_equipment', 8500, null, 'low', 'Admin', false, 'completed',
   '{"category":"office_equipment","department":"Admin","priority":"low","approvalRequired":false,"reason":"Low value consumables are handled by Admin without approval."}'::jsonb,
   null, null, null, now() - interval '30 days'),

  ((select id from public.users where email = 'ks@irs.com.my'),
   'Printer in the meeting room jams constantly',
   'The meeting room printer jams on every second job and needs repair.',
   'it_equipment', 0, null, 'high', 'IT', true, 'pending_approval',
   '{"category":"it_equipment","department":"IT","priority":"high","approvalRequired":true,"reason":"Repair work is raised at high priority."}'::jsonb,
   null, null, null, now() - interval '2 days');

-- A short conversation on the requests still being handled.
insert into public.request_comments (request_id, author_id, body, created_time)
select r.id, (select id from public.users where email = 'hr@irs.com.my'),
       'Supplier quoted two weeks. I will update once it ships.',
       now() - interval '8 days'
  from public.requests r where r.title = 'Ergonomic chair replacement';

insert into public.request_comments (request_id, author_id, body, created_time)
select r.id, r.requester_id,
       'Thank you. The current chair is usable in the meantime.',
       now() - interval '7 days'
  from public.requests r where r.title = 'Ergonomic chair replacement';

insert into public.request_comments (request_id, author_id, body, created_time)
select r.id, (select id from public.users where email = 'hr@irs.com.my'),
       'Raised with the building manager, they are attending this week.',
       now() - interval '2 days'
  from public.requests r where r.title = 'Access card not opening the back door';

-- Matching audit trail, so the log is not empty for the requests module.
insert into public.automation_logs (
  action_type, description, related_table, related_id, performed_by,
  is_system, created_time
)
select
  case r.status
    when 'approved' then 'request.approved'
    when 'rejected' then 'request.rejected'
    when 'in_progress' then 'request.in_progress'
    when 'completed' then 'request.completed'
    else 'request.submitted'
  end,
  format('%s — %s', u.full_name, r.title),
  'requests',
  r.id,
  coalesce(r.reviewed_by, r.requester_id),
  false,
  coalesce(r.reviewed_at, r.created_time)
from public.requests r
join public.users u on u.id = r.requester_id;
